/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sqli.composablehub.algolia.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ArticleTarget extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2983332045109780359L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ArticleTarget\",\"namespace\":\"com.sqli.composablehub.algolia.models\",\"fields\":[{\"name\":\"objectID\",\"type\":\"string\",\"doc\":\"Mapped to Catalog_version + Product ID. This is the only required attribute for algolia\"},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"catalog_version\",\"type\":\"string\"},{\"name\":\"integration_key\",\"type\":\"string\"},{\"name\":\"supercategories\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ArticleTarget> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ArticleTarget> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ArticleTarget> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ArticleTarget> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ArticleTarget> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ArticleTarget to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ArticleTarget from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ArticleTarget instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ArticleTarget fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Mapped to Catalog_version + Product ID. This is the only required attribute for algolia */
  private java.lang.CharSequence objectID;
  private java.lang.CharSequence code;
  private java.lang.CharSequence catalog_version;
  private java.lang.CharSequence integration_key;
  private java.util.List<java.lang.CharSequence> supercategories;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ArticleTarget() {}

  /**
   * All-args constructor.
   * @param objectID Mapped to Catalog_version + Product ID. This is the only required attribute for algolia
   * @param code The new value for code
   * @param catalog_version The new value for catalog_version
   * @param integration_key The new value for integration_key
   * @param supercategories The new value for supercategories
   */
  public ArticleTarget(java.lang.CharSequence objectID, java.lang.CharSequence code, java.lang.CharSequence catalog_version, java.lang.CharSequence integration_key, java.util.List<java.lang.CharSequence> supercategories) {
    this.objectID = objectID;
    this.code = code;
    this.catalog_version = catalog_version;
    this.integration_key = integration_key;
    this.supercategories = supercategories;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return objectID;
    case 1: return code;
    case 2: return catalog_version;
    case 3: return integration_key;
    case 4: return supercategories;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: objectID = (java.lang.CharSequence)value$; break;
    case 1: code = (java.lang.CharSequence)value$; break;
    case 2: catalog_version = (java.lang.CharSequence)value$; break;
    case 3: integration_key = (java.lang.CharSequence)value$; break;
    case 4: supercategories = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'objectID' field.
   * @return Mapped to Catalog_version + Product ID. This is the only required attribute for algolia
   */
  public java.lang.CharSequence getObjectID() {
    return objectID;
  }


  /**
   * Sets the value of the 'objectID' field.
   * Mapped to Catalog_version + Product ID. This is the only required attribute for algolia
   * @param value the value to set.
   */
  public void setObjectID(java.lang.CharSequence value) {
    this.objectID = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'catalog_version' field.
   * @return The value of the 'catalog_version' field.
   */
  public java.lang.CharSequence getCatalogVersion() {
    return catalog_version;
  }


  /**
   * Sets the value of the 'catalog_version' field.
   * @param value the value to set.
   */
  public void setCatalogVersion(java.lang.CharSequence value) {
    this.catalog_version = value;
  }

  /**
   * Gets the value of the 'integration_key' field.
   * @return The value of the 'integration_key' field.
   */
  public java.lang.CharSequence getIntegrationKey() {
    return integration_key;
  }


  /**
   * Sets the value of the 'integration_key' field.
   * @param value the value to set.
   */
  public void setIntegrationKey(java.lang.CharSequence value) {
    this.integration_key = value;
  }

  /**
   * Gets the value of the 'supercategories' field.
   * @return The value of the 'supercategories' field.
   */
  public java.util.List<java.lang.CharSequence> getSupercategories() {
    return supercategories;
  }


  /**
   * Sets the value of the 'supercategories' field.
   * @param value the value to set.
   */
  public void setSupercategories(java.util.List<java.lang.CharSequence> value) {
    this.supercategories = value;
  }

  /**
   * Creates a new ArticleTarget RecordBuilder.
   * @return A new ArticleTarget RecordBuilder
   */
  public static com.sqli.composablehub.algolia.models.ArticleTarget.Builder newBuilder() {
    return new com.sqli.composablehub.algolia.models.ArticleTarget.Builder();
  }

  /**
   * Creates a new ArticleTarget RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ArticleTarget RecordBuilder
   */
  public static com.sqli.composablehub.algolia.models.ArticleTarget.Builder newBuilder(com.sqli.composablehub.algolia.models.ArticleTarget.Builder other) {
    if (other == null) {
      return new com.sqli.composablehub.algolia.models.ArticleTarget.Builder();
    } else {
      return new com.sqli.composablehub.algolia.models.ArticleTarget.Builder(other);
    }
  }

  /**
   * Creates a new ArticleTarget RecordBuilder by copying an existing ArticleTarget instance.
   * @param other The existing instance to copy.
   * @return A new ArticleTarget RecordBuilder
   */
  public static com.sqli.composablehub.algolia.models.ArticleTarget.Builder newBuilder(com.sqli.composablehub.algolia.models.ArticleTarget other) {
    if (other == null) {
      return new com.sqli.composablehub.algolia.models.ArticleTarget.Builder();
    } else {
      return new com.sqli.composablehub.algolia.models.ArticleTarget.Builder(other);
    }
  }

  /**
   * RecordBuilder for ArticleTarget instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ArticleTarget>
    implements org.apache.avro.data.RecordBuilder<ArticleTarget> {

    /** Mapped to Catalog_version + Product ID. This is the only required attribute for algolia */
    private java.lang.CharSequence objectID;
    private java.lang.CharSequence code;
    private java.lang.CharSequence catalog_version;
    private java.lang.CharSequence integration_key;
    private java.util.List<java.lang.CharSequence> supercategories;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sqli.composablehub.algolia.models.ArticleTarget.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.objectID)) {
        this.objectID = data().deepCopy(fields()[0].schema(), other.objectID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.catalog_version)) {
        this.catalog_version = data().deepCopy(fields()[2].schema(), other.catalog_version);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.integration_key)) {
        this.integration_key = data().deepCopy(fields()[3].schema(), other.integration_key);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.supercategories)) {
        this.supercategories = data().deepCopy(fields()[4].schema(), other.supercategories);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ArticleTarget instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sqli.composablehub.algolia.models.ArticleTarget other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.objectID)) {
        this.objectID = data().deepCopy(fields()[0].schema(), other.objectID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.catalog_version)) {
        this.catalog_version = data().deepCopy(fields()[2].schema(), other.catalog_version);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.integration_key)) {
        this.integration_key = data().deepCopy(fields()[3].schema(), other.integration_key);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.supercategories)) {
        this.supercategories = data().deepCopy(fields()[4].schema(), other.supercategories);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'objectID' field.
      * Mapped to Catalog_version + Product ID. This is the only required attribute for algolia
      * @return The value.
      */
    public java.lang.CharSequence getObjectID() {
      return objectID;
    }


    /**
      * Sets the value of the 'objectID' field.
      * Mapped to Catalog_version + Product ID. This is the only required attribute for algolia
      * @param value The value of 'objectID'.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder setObjectID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.objectID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'objectID' field has been set.
      * Mapped to Catalog_version + Product ID. This is the only required attribute for algolia
      * @return True if the 'objectID' field has been set, false otherwise.
      */
    public boolean hasObjectID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'objectID' field.
      * Mapped to Catalog_version + Product ID. This is the only required attribute for algolia
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder clearObjectID() {
      objectID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder clearCode() {
      code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'catalog_version' field.
      * @return The value.
      */
    public java.lang.CharSequence getCatalogVersion() {
      return catalog_version;
    }


    /**
      * Sets the value of the 'catalog_version' field.
      * @param value The value of 'catalog_version'.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder setCatalogVersion(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.catalog_version = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'catalog_version' field has been set.
      * @return True if the 'catalog_version' field has been set, false otherwise.
      */
    public boolean hasCatalogVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'catalog_version' field.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder clearCatalogVersion() {
      catalog_version = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'integration_key' field.
      * @return The value.
      */
    public java.lang.CharSequence getIntegrationKey() {
      return integration_key;
    }


    /**
      * Sets the value of the 'integration_key' field.
      * @param value The value of 'integration_key'.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder setIntegrationKey(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.integration_key = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'integration_key' field has been set.
      * @return True if the 'integration_key' field has been set, false otherwise.
      */
    public boolean hasIntegrationKey() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'integration_key' field.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder clearIntegrationKey() {
      integration_key = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'supercategories' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getSupercategories() {
      return supercategories;
    }


    /**
      * Sets the value of the 'supercategories' field.
      * @param value The value of 'supercategories'.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder setSupercategories(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.supercategories = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'supercategories' field has been set.
      * @return True if the 'supercategories' field has been set, false otherwise.
      */
    public boolean hasSupercategories() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'supercategories' field.
      * @return This builder.
      */
    public com.sqli.composablehub.algolia.models.ArticleTarget.Builder clearSupercategories() {
      supercategories = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ArticleTarget build() {
      try {
        ArticleTarget record = new ArticleTarget();
        record.objectID = fieldSetFlags()[0] ? this.objectID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.catalog_version = fieldSetFlags()[2] ? this.catalog_version : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.integration_key = fieldSetFlags()[3] ? this.integration_key : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.supercategories = fieldSetFlags()[4] ? this.supercategories : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ArticleTarget>
    WRITER$ = (org.apache.avro.io.DatumWriter<ArticleTarget>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ArticleTarget>
    READER$ = (org.apache.avro.io.DatumReader<ArticleTarget>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.objectID);

    out.writeString(this.code);

    out.writeString(this.catalog_version);

    out.writeString(this.integration_key);

    long size0 = this.supercategories.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.supercategories) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.objectID = in.readString(this.objectID instanceof Utf8 ? (Utf8)this.objectID : null);

      this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);

      this.catalog_version = in.readString(this.catalog_version instanceof Utf8 ? (Utf8)this.catalog_version : null);

      this.integration_key = in.readString(this.integration_key instanceof Utf8 ? (Utf8)this.integration_key : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.supercategories;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("supercategories").schema());
        this.supercategories = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.objectID = in.readString(this.objectID instanceof Utf8 ? (Utf8)this.objectID : null);
          break;

        case 1:
          this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          break;

        case 2:
          this.catalog_version = in.readString(this.catalog_version instanceof Utf8 ? (Utf8)this.catalog_version : null);
          break;

        case 3:
          this.integration_key = in.readString(this.integration_key instanceof Utf8 ? (Utf8)this.integration_key : null);
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.supercategories;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("supercategories").schema());
            this.supercategories = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










